# Generated by Django 3.2.12 on 2022-07-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220721_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_team',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='team_name',
        ),
    ]
