# Generated by Django 4.2.3 on 2024-08-07 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 11, 18, 47, 466399, tzinfo=datetime.timezone.utc)),
        ),
    ]
