# Generated by Django 3.2.12 on 2022-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.SmallIntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
