# Generated by Django 3.2.12 on 2022-07-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_auto_20220710_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.CharField(max_length=50),
        ),
    ]
