# Generated by Django 3.2.12 on 2022-07-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_alter_player_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
    ]
