# Generated by Django 3.2.12 on 2022-07-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
