# Generated by Django 3.2.12 on 2022-07-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_player_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
