# Generated by Django 3.2.12 on 2022-07-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_auto_20220722_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='players',
            new_name='player',
        ),
    ]
