# Generated by Django 3.2.12 on 2022-07-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_remove_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
