# Generated by Django 3.2.12 on 2022-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0018_player_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(),
        ),
    ]
