# Generated by Django 3.2.12 on 2022-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0019_auto_20220727_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
