# Generated by Django 3.2.12 on 2022-07-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_alter_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='league',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
