# Generated by Django 3.2.12 on 2022-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='fantasy.Player'),
        ),
    ]
