# Generated by Django 3.2.12 on 2022-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0024_auto_20220731_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='value',
            field=models.FloatField(default=500),
        ),
    ]
