# Generated by Django 3.2.12 on 2022-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_team_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='value',
            field=models.FloatField(),
        ),
    ]
