# Generated by Django 3.2.12 on 2022-08-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0027_remove_team_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
