# Generated by Django 3.2.12 on 2022-08-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0028_tactics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tactics',
            new_name='Tactic',
        ),
    ]
