# Generated by Django 3.2.12 on 2022-08-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0029_rename_tactics_tactic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
