# Generated by Django 3.2.12 on 2022-08-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0030_remove_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
