# Generated by Django 3.2.12 on 2022-08-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0031_team_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='valid',
        ),
    ]
