# Generated by Django 3.2.12 on 2022-08-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0033_validteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidTeam',
        ),
    ]
