# Generated by Django 3.2.12 on 2022-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0034_delete_validteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
