# Generated by Django 3.2.12 on 2022-08-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0038_alter_player_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-value']},
        ),
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
