# Generated by Django 3.2.12 on 2022-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0039_auto_20220823_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conceded',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scored',
            field=models.SmallIntegerField(default=0),
        ),
    ]
