# Generated by Django 3.2.12 on 2022-08-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0040_auto_20220823_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='conceded',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scored',
        ),
        migrations.AddField(
            model_name='club',
            name='conceded',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='scored',
            field=models.SmallIntegerField(default=0),
        ),
    ]
