# Generated by Django 3.2.12 on 2022-08-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0041_auto_20220824_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.SmallIntegerField(default=0),
        ),
    ]
