# Generated by Django 3.2.12 on 2022-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0042_auto_20220827_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.SmallIntegerField(default=0),
        ),
    ]
