# Generated by Django 3.2.12 on 2022-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0043_player_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='draws',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='losses',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='wins',
            field=models.SmallIntegerField(default=0),
        ),
    ]
