# Generated by Django 3.2.12 on 2022-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0044_auto_20220829_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
