# Generated by Django 3.2.12 on 2022-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0045_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
