# Generated by Django 3.2.12 on 2022-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0047_league_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
