# Generated by Django 3.2.12 on 2022-09-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0048_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='place',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
