# Generated by Django 3.2.12 on 2022-09-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0049_auto_20220911_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.SmallIntegerField(default=0),
        ),
    ]
