# Generated by Django 3.2.12 on 2022-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0050_team_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
