# Generated by Django 3.2.12 on 2022-10-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0052_player_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.SmallIntegerField(default=0),
        ),
    ]
