# Generated by Django 3.2.12 on 2022-10-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0054_player_second_yellow_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='flag',
        ),
    ]
