# Generated by Django 3.2.12 on 2022-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0056_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='relegation_places',
            field=models.SmallIntegerField(default=0),
        ),
    ]
