# Generated by Django 3.2.12 on 2022-11-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0057_league_relegation_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='place_change',
            field=models.SmallIntegerField(default=0),
        ),
    ]
