# Generated by Django 3.2.12 on 2022-11-05 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0059_auto_20221104_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.SmallIntegerField(default=0),
        ),
    ]
