# Generated by Django 3.2.12 on 2022-11-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0060_auto_20221105_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
