# Generated by Django 3.2.12 on 2022-11-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0061_auto_20221115_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': []},
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
