# Generated by Django 3.2.12 on 2022-12-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0062_auto_20221126_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.CharField(default='', max_length=50)),
                ('age', models.SmallIntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('wins', models.SmallIntegerField(default=0)),
                ('draws', models.SmallIntegerField(default=0)),
                ('losses', models.SmallIntegerField(default=0)),
                ('club', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.club')),
            ],
        ),
    ]
