# Generated by Django 3.2.12 on 2022-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0065_league_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='country',
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
