# Generated by Django 3.2.12 on 2022-12-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0066_auto_20221214_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confederation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='nation',
            name='flag',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='nation',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='nation',
            name='confederation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.confederation'),
        ),
    ]
