# Generated by Django 3.2.12 on 2022-12-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0069_player_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='flag_url',
            field=models.URLField(default=''),
        ),
    ]
