# Generated by Django 3.2.12 on 2022-12-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0071_auto_20221215_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='flag',
        ),
    ]
