# Generated by Django 3.2.12 on 2022-12-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0073_auto_20221216_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.club'),
        ),
    ]
