# Generated by Django 3.2.12 on 2023-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0077_match_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='ams',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='cbs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='cfs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='cms',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='dms',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='lbs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='lws',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='rbs',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tactic',
            name='rws',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
