# Generated by Django 3.2.12 on 2023-01-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0081_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scorers',
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.SmallIntegerField(default=0)),
                ('type', models.CharField(default='', max_length=50)),
                ('scorer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.player')),
            ],
        ),
    ]
