# Generated by Django 3.2.12 on 2023-01-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0083_auto_20230117_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='minute',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.player'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
