# Generated by Django 3.2.12 on 2023-01-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0085_auto_20230117_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
    ]
