# Generated by Django 3.2.12 on 2023-01-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0086_remove_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=30)),
                ('image_url', models.URLField(default='')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='value',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='wins',
        ),
        migrations.AddField(
            model_name='coach',
            name='nation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.nation'),
        ),
        migrations.AddField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(to='fantasy.PollChoice'),
        ),
    ]
