# Generated by Django 3.2.12 on 2023-01-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0087_auto_20230119_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='type',
        ),
    ]
