# Generated by Django 3.2.12 on 2023-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0088_remove_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='text',
            field=models.CharField(default='', max_length=50),
        ),
    ]
