# Generated by Django 4.1.5 on 2023-01-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0089_alter_pollchoice_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groups', models.SmallIntegerField(default=0)),
                ('teams_per_group', models.SmallIntegerField(default=0)),
                ('confederation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.confederation')),
            ],
        ),
    ]
