# Generated by Django 4.1.5 on 2023-01-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0091_clubcup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='internationalcup',
            name='confederation',
        ),
        migrations.AddField(
            model_name='club',
            name='int_points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ClubCup',
        ),
        migrations.DeleteModel(
            name='InternationalCup',
        ),
    ]
