# Generated by Django 4.1.5 on 2023-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0092_cup_remove_internationalcup_confederation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('POLL', 'Poll'), ('QUIZ', 'Quiz')], default='', max_length=20),
        ),
    ]
