# Generated by Django 4.1.5 on 2023-01-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0093_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('POLL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team')), ('QUIZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.club'))], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='image_url',
            field=models.URLField(default='', max_length=10000),
        ),
    ]
