# Generated by Django 4.1.5 on 2023-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0094_alter_poll_type_alter_pollchoice_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('POLL', models.ManyToManyField(to='fantasy.player')), ('QUIZ', models.ManyToManyField(to='fantasy.club'))], default='', max_length=20),
        ),
    ]
