# Generated by Django 4.1.5 on 2023-01-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0096_clubscup_cupmatch_delete_cup_remove_match_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubscup',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='clubscup',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
