# Generated by Django 4.1.5 on 2023-01-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0098_remove_leaguematch_league_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='clubcup',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='leaguekey',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchdaynum',
            new_name='matchday',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='stagenum',
            new_name='stage',
        ),
    ]
