# Generated by Django 4.1.5 on 2023-02-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0099_rename_clubcup_match_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='club',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.DeleteModel(
            name='ClubsCup',
        ),
    ]
