# Generated by Django 4.1.5 on 2023-02-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0101_club_points_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='points_history',
            new_name='table_history',
        ),
    ]
