# Generated by Django 4.1.5 on 2023-02-05 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0102_rename_points_history_club_table_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='table_history',
            field=models.CharField(default='', max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
