# Generated by Django 4.1.5 on 2023-02-05 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0104_alter_club_table_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='datetime',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
