# Generated by Django 4.1.5 on 2023-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0105_remove_match_datetime_match_date_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
