# Generated by Django 4.1.5 on 2023-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0106_alter_match_date_alter_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('PAST', 'Past'), ('NEXT', 'Next')], default='', max_length=10),
        ),
    ]
