# Generated by Django 4.1.5 on 2023-02-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0107_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='matchdays_url',
            field=models.URLField(default=''),
        ),
    ]
