# Generated by Django 4.1.5 on 2023-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0108_league_matchdays_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='table_history',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
