# Generated by Django 4.1.5 on 2023-06-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0109_alter_club_table_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='choiceid',
            field=models.SmallIntegerField(default=0),
        ),
    ]
