# Generated by Django 4.1.5 on 2023-06-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0111_player_number_of_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number_of_queries',
        ),
        migrations.AddField(
            model_name='player',
            name='popularity_number',
            field=models.FloatField(default=0),
        ),
    ]
