# Generated by Django 4.1.5 on 2023-06-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0112_remove_player_number_of_queries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
