# Generated by Django 4.2.3 on 2024-06-16 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantasy', '0113_poll_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='UserTeam',
        ),
        migrations.RemoveField(
            model_name='club',
            name='league',
        ),
    ]
