# Generated by Django 4.2.3 on 2024-06-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0114_rename_team_userteam_remove_club_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('points', models.SmallIntegerField(default=0)),
                ('int_points', models.SmallIntegerField(default=0)),
                ('place', models.SmallIntegerField(default=0)),
                ('place_change', models.SmallIntegerField(default=0)),
                ('url', models.URLField(default='')),
                ('logo_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.team')),
                ('table_history', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=('fantasy.team',),
        ),
        migrations.CreateModel(
            name='NationalTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fantasy.team')),
            ],
            bases=('fantasy.team',),
        ),
        migrations.AlterField(
            model_name='coach',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='fantasy.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='fantasy.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.team'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='logo',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.team'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
