# Generated by Django 4.2.3 on 2024-06-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0115_team_clubteam_nationalteam_alter_coach_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='apiID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='birtdate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='fastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
