# Generated by Django 4.2.3 on 2024-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0116_player_apiid_player_birtdate_player_fastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='coach',
            old_name='nation',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='birtdate',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nation',
            new_name='nationality',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='shirtNumber',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fastName',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.AddField(
            model_name='coach',
            name='apiID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coach',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
