# Generated by Django 4.2.3 on 2024-06-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0117_rename_name_coach_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiID', models.IntegerField(default=0)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField()),
                ('nationality', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.nation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
