# Generated by Django 4.2.3 on 2024-06-19 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0118_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('location', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('yearOpened', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clubteam',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nationalteam',
            name='confederation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.confederation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationalteam',
            name='fifaRank',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.URLField(default='')),
                ('participants', models.ManyToManyField(to='fantasy.team')),
            ],
        ),
        migrations.AddField(
            model_name='clubteam',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fantasy.stadium'),
        ),
    ]
