# Generated by Django 4.2.3 on 2024-07-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0120_remove_league_id_remove_league_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='url',
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(default='', null=True),
        ),
    ]
