# Generated by Django 4.2.3 on 2024-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0121_remove_team_url_alter_team_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
