# Generated by Django 4.2.3 on 2024-08-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directchat', '0005_remove_chatroom_id_remove_chatroom_name_and_more'),
        ('blog', '0008_alter_fanclub_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanclub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fanclub',
            name='members',
        ),
        migrations.AddField(
            model_name='fanclub',
            name='room_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='directchat.room'),
            preserve_default=False,
        ),
    ]
